### ISSUE TITLE
Error during cython compilation

### ISSUE THREAD

**Issue by AntoinespacePierre** [TheStageAI/TorchIntegral#10]
Hello,

While trying to coùmpile the project from branch main, I encountered an error :  

"torch_integral/tsp_solver/solver.pyx:224:9: 'vector' is not a type identifier" 

which prevented the cython file tsp_solver from compiling. I apparently fixed it by adding : 

"from libcpp.vector cimport vector" 

in the file though I didn't test the code yet but the project compiled. I noticed that in the fix branch, this import is present along with other cpp imports that were removed from branch main in pull request #7. I respectfully suggest you check the imports or perhaps change the code as in https://stackoverflow.com/questions/24659723/cython-issue-bool-is-not-a-type-identifier if you don't want the imports.

Please, let me know if I made a mistake and I apologize for the inconvenience.
Thank you

**Comment by ArnoldMSU** [comment]
Hello @AntoinespacePierre ! There was error in vector import. Now it is fixed

**Comment by AntoinespacePierre** [comment]
Thank you
