### ISSUE TITLE
no module named 'torch_integral.tsp_solver.solver'

### ISSUE THREAD

**Issue by sangfeel** [TheStageAI/TorchIntegral#16]
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-6-f4618bc450a4>](https://localhost:8080/#) in <cell line: 3>()
      1 get_ipython().run_line_magic('cd', '"/content/drive/MyDrive/TorchIntegral/"')
      2 import torch
----> 3 import torch_integral as inn
      4 from torchvision.models import resnet18
      5 

3 frames
[/content/drive/MyDrive/TorchIntegral/torch_integral/__init__.py](https://localhost:8080/#) in <module>
----> 1 from .model import IntegralWrapper
      2 from .model import IntegralModel
      3 from .graph import IntegralTracer
      4 from .grid import UniformDistribution
      5 from .grid import NormalDistribution

[/content/drive/MyDrive/TorchIntegral/torch_integral/model.py](https://localhost:8080/#) in <module>
      9 from .parametrizations import InterpolationWeights1D
     10 from .parametrizations import InterpolationWeights2D
---> 11 from .permutation import NOptPermutation
     12 from .quadrature import TrapezoidalQuadrature
     13 from .grid import TrainableGrid1D

[/content/drive/MyDrive/TorchIntegral/torch_integral/permutation.py](https://localhost:8080/#) in <module>
      1 import torch
----> 2 from .tsp_solver import two_opt_find_permutation
      3 
      4 
      5 def total_variance(tensors):

[/content/drive/MyDrive/TorchIntegral/torch_integral/tsp_solver/__init__.py](https://localhost:8080/#) in <module>
----> 1 from .solver import two_opt_find_permutation

ModuleNotFoundError: No module named 'torch_integral.tsp_solver.solver'

i running at colab. But I got this error.

**Comment by b1n0** [comment]
You should install TorchIntegral lib before importing because it contains cython code. Use pip install TorchIntegral/

**Comment by sangfeel** [comment]
![image](https://github.com/TheStageAI/TorchIntegral/assets/98583511/415cfbd9-9c7a-4809-9da0-5fae569ac275)

https://colab.research.google.com/drive/1MeCJgwarA-XWM-loVKyEddh7znpUn4bB?usp=sharing

i already instll torchintegral lib.  This link is my colab link. Please help me

**Comment by b1n0** [comment]
It works if command before import %cd "/content/drive/MyDrive/TorchIntegral/" is removed. Check this [google colab notebook](https://colab.research.google.com/drive/140Oo5GYkn6bk21Lvl2Rb1J-ZPhqq8rKZ?usp=sharing).

**Comment by sangfeel** [comment]
Oh I solve problem.Thank u so much!!

**Comment by b1n0** [comment]
Great! I close the issue, feel free to reopen.
