### ISSUE TITLE
About continuous_dims

### ISSUE THREAD

**Issue by sangfeel** [TheStageAI/TorchIntegral#17]
continuous_dims = {
        "layer4.0.conv1.weight": [0, 1],
        "layer4.0.conv2.weight": [0, 1],
        "layer4.0.downsample.0.weight": [0, 1],
        "layer4.1.conv1.weight": [0, 1],
        "layer4.1.conv2.weight": [0, 1],
    }
    
Above is the definition of continuous_dim in imagnet.py .

The question is, what are the criteria for determining continuous_dim. Described as continuous_dim performing the crop. If so, do I have to choose all the parts that correspond to the last layer before entering the fully connected layer?

Additionally, in the example above, that's how it works
import torch
Bringing a torch to an inn
Get .reset back from torchvision 18

Model = resnet18 (pre-training = true)
Wrapping paper = Inn.All-in-one wrapper (init_from_discrete=True)

 Specify continuous dimensions to cut
Continuous_dims = {
"Tier 4.0.conv1.weight": [0],
"Tier 4.1.conv1"Weight": [0, 1]
}

 Converting to an integrated model
in_model = rapper (model, (1, 3, 224, 224), continuous_dims)

The choice of continuous_dims is slightly different here. I would appreciate it if you could tell me the difference between these two as well.

**Comment by ArnoldMSU** [comment]
Hello @sangfeel ! Please start discussion instead of starting Issues in similar cases.

**Comment by sangfeel** [comment]
> continuous_dims = { "layer4.0.conv1.weight": [0, 1], "layer4.0.conv2.weight": [0, 1], "layer4.0.downsample.0.weight": [0, 1], "layer4.1.conv1.weight": [0, 1], "layer4.1.conv2.weight": [0, 1], }
> 
> Above is the definition of continuous_dim in imagnet.py .
> 
> The question is, what are the criteria for determining continuous_dim. Described as continuous_dim performing the crop. If so, do I have to choose all the parts that correspond to the last layer before entering the fully connected layer?
> 
> Additionally, in the example above, that's how it works import torch Bringing a torch to an inn Get .reset back from torchvision 18
> 
> Model = resnet18 (pre-training = true) Wrapping paper = Inn.All-in-one wrapper (init_from_discrete=True)
> 
> Specify continuous dimensions to cut Continuous_dims = { "Tier 4.0.conv1.weight": [0], "Tier 4.1.conv1"Weight": [0, 1] }
> 
> Converting to an integrated model in_model = rapper (model, (1, 3, 224, 224), continuous_dims)
> 
> The choice of continuous_dims is slightly different here. I would appreciate it if you could tell me the difference between these two as well.



> Hello @sangfeel ! Please start discussion instead of starting Issues in similar cases.

Sorry. This activity is my first github. I start discussion.
