### ISSUE TITLE
where is the transform_to_discrete method?

### ISSUE THREAD

**Issue by JBartholomewMN** [TheStageAI/TorchIntegral#23]
The readme states that the IntegralWrapper class should have a method "transform_to_discrete". But this method does not exist. 

So how do we convert an integral model into a discrete one?

**Comment by b1n0** [comment]
Yeah, need to update readme. Use ‎get_unparametrized_model method instead.

**Comment by JBartholomewMN** [comment]
when I call get_unparametrized_model method and then inspect the returned model, there still is parameterized convolutions in the model. I guess I'm not expecting this to be true because I thought this method should return a discrete model. for example, this is what I see.

```
ParametrizedConv2d(
  1024, 512, kernel_size=(1, 1), stride=(1, 1)
  (parametrizations): ModuleDict(
    (weight): ParametrizationList(
      (0): GridSampleWeights2D(
        (quadrature): TrapezoidalQuadrature()
        (grid): GridND(
          (grid_objects): ModuleList(
            (0-1): 2 x RandomLinspace()
          )
        )
      )
    )
    (bias): ParametrizationList(
      (0): GridSampleWeights1D(
        (grid): GridND(
          (grid_objects): ModuleList(
            (0): RandomLinspace()
          )
        )
      )
    )
  )
)
```

**Comment by b1n0** [comment]
Thanks for bug report. Update the lib it should work now.

**Comment by JBartholomewMN** [comment]
so I think there is still a bug with the unparametrized model - it is not being generated cleanly
```
from terralearn.models.components.clip import HackedCLIPRN50
from torch_integral import UniformDistribution, IntegralWrapper
from torchvision import models
import torch

ref = models.resnet18(weights=models.ResNet18_Weights.DEFAULT).cuda()

continuous_dims = {
    "layer4.1.conv1.weight": [0, 1],
    "layer4.1.conv2.weight": [0, 1],
}
wrapper = IntegralWrapper(init_from_discrete=True)

model = wrapper(ref, [1, 3, 768, 768], continuous_dims=continuous_dims)

for i, _ in enumerate(model.groups):
    model.groups[i].resize(338)

compressed = model.eval().get_unparametrized_model()

assert (
    compressed.layer4[1].conv1.weight.shape[0] == compressed.layer4[1].conv1.in_channels
), "the weight matrix does not correspond to the in_channels of the layer"
```

produces Traceback (most recent call last):
  File "<string>", line 2, in <module>
AssertionError: the weight matrix does not correspond to the in_channels of the layer

**Comment by b1n0** [comment]
Attributes `in_channels` and `out_channels` of the conv layer are not modified after pruning.
Check better this:
assert (compressed.layer4[1].conv1.weight.shape[0] == compressed.layer4[1].conv1.shape[1])

both equal to 338

**Comment by JBartholomewMN** [comment]
I guess I'm trying to point out that they **should** be changed after pruning because it's possible that downstream software depends upon these member variables being correct. Sometimes models are programmatically constructed and it's misleading to change only the weight matrix but then leave the layer's metadata incorrect.

**Comment by b1n0** [comment]
This is a good point, we will take it into account.

**Comment by JBartholomewMN** [comment]
Was this actually implemented? Why was this marked as closed? Usually it's considered good practice to comment on your plans when you close an issue: either that you will fix it, plan it for the future, or take no action.

**Comment by Adamdad** [comment]
Indeed, the mismatch between `module.in_channel/out_channel` the actual `weight.shape` is a very serious problem. I spend hours to see what is wrong with my model. Hope the author can fix this soon.
