### ISSUE TITLE
Memory leak or greedy memory usage

### ISSUE THREAD

**Issue by warpuv** [TheStageAI/TorchIntegral#34]
If you call `gc.collect()` at the end of `build_groups()` function (right before `return self.groups` statement) this will significantly reduce memory usage. It is better to call `gc.collect()` manually here because you use data structure with reference cycles. This fix allows wrapping some large models, which was not possible without that fix.

**Comment by b1n0** [comment]
Good point, thanks, Ura. 
Added gc.collect
